In [22]:
import pandas as pd
df=pd.read_csv("ai_impact_jobs_2010_2025.csv")
df

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,...,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,...,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,...,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
3,05c1c7d3-2add-4919-91eb-f6c78bfe23d1,2015,Spain,Europe,Nairobi,Global Technologies,Large,Government,Data Scientist,Mid,...,0.19,"Cloud Computing, SQL, Project Management, Comm...",NaN,72894,-2.80,0.70,False,Low,15,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,...,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,45aa223b-3ed6-4574-bd07-294a1443c02b,2022,Singapore,Southeast Asia,Bangalore,Prime Analytics,Enterprise,Education,ML Engineer,Intern,...,0.12,"SQL, Project Management, Data Analysis",NaN,41317,4.62,0.88,False,Low,17,Growing
4996,9f69f4ce-5fe9-44db-9541-478ebe28422b,2018,Chile,South America,Sydney,Future Analytics,Large,Healthcare,Policy Analyst,Senior,...,0.07,"Software Engineering, Statistics, Business Ana...",NaN,37089,-4.26,0.79,False,Low,13,Growing
4997,0ec6f97e-6dc3-468c-b2a2-ecc087bf067e,2019,Australia,Oceania,Bangalore,Global Solutions,Large,Education,ML Engineer,Mid,...,0.05,"Project Management, Data Analysis, Business An...",NaN,81651,-4.95,0.64,False,Low,19,Growing
4998,ad529cef-b22e-4e7d-82fd-98fc06d61596,2016,Sweden,Europe,Sydney,NextGen Systems,Enterprise,Energy,AI Researcher,Junior,...,0.87,"SQL, Research, Cloud Computing, Communication,...","computer vision, MLOps",107897,-0.23,0.33,True,Low,14,Emerging
4999,79d26161-8cc1-4d98-ab0d-3ebea91f2a1b,2024,India,South Asia,Tokyo,Future Analytics,Enterprise,Tech,Software Engineer,Executive,...,0.56,"Software Engineering, Project Management, Busi...",LLMs,35755,11.00,0.10,True,Low,11,Mature

In [23]:
import pandas as pd
df=pd.read_csv("ai_impact_jobs_2010_2025.csv")
print(df)

                                    job_id  posting_year    country  \
0     836b4774-702e-49ef-93d3-2f255ce1e910          2018     Brazil
1     43699e93-7b15-4728-a4c6-9e41ff438a25          2015        UAE
2     fc9d1854-3cbf-4bab-90df-77304dfc59df          2016      Nepal
3     05c1c7d3-2add-4919-91eb-f6c78bfe23d1          2015      Spain
4     5e739937-d1b0-44d7-935c-7ebb3fc1f6e8          2014     Taiwan
...                                    ...           ...        ...
4995  45aa223b-3ed6-4574-bd07-294a1443c02b          2022  Singapore
4996  9f69f4ce-5fe9-44db-9541-478ebe28422b          2018      Chile
4997  0ec6f97e-6dc3-468c-b2a2-ecc087bf067e          2019  Australia
4998  ad529cef-b22e-4e7d-82fd-98fc06d61596          2016     Sweden
4999  79d26161-8cc1-4d98-ab0d-3ebea91f2a1b          2024      India

              region       city          company_name company_size  \
0      South America     London  NextGen Technologies        Small
1        Middle East  Singapore      Future Solutions       Medium
2         South Asia     Sydney      Future Analytics      Startup
3             Europe    Nairobi   Global Technologies        Large
4          East Asia     Sydney   Future Technologies        Small
...              ...        ...                   ...          ...
4995  Southeast Asia  Bangalore       Prime Analytics   Enterprise
4996   South America     Sydney      Future Analytics        Large
4997         Oceania  Bangalore      Global Solutions        Large
4998          Europe     Sydney       NextGen Systems   Enterprise
4999      South Asia      Tokyo      Future Analytics   Enterprise

           industry          job_title seniority_level  ...  \
0         Education     Policy Analyst            Lead  ...
1            Energy     Data Scientist       Executive  ...
2           Finance    Product Manager          Junior  ...
3        Government     Data Scientist             Mid  ...
4     Manufacturing        ML Engineer            Lead  ...
...             ...                ...             ...  ...
4995      Education        ML Engineer          Intern  ...
4996     Healthcare     Policy Analyst          Senior  ...
4997      Education        ML Engineer             Mid  ...
4998         Energy      AI Researcher          Junior  ...
4999           Tech  Software Engineer       Executive  ...

      ai_intensity_score                                        core_skills  \
0                   0.81    Research, Project Management, Business Analysis
1                   0.04  Research, SQL, Business Analysis, Python, Clou...
2                   0.15  Statistics, Project Management, Cloud Computin...
3                   0.19  Cloud Computing, SQL, Project Management, Comm...
4                   0.11  SQL, Python, Communication, Software Engineeri...
...                  ...                                                ...
4995                0.12             SQL, Project Management, Data Analysis
4996                0.07  Software Engineering, Statistics, Business Ana...
4997                0.05  Project Management, Data Analysis, Business An...
4998                0.87  SQL, Research, Cloud Computing, Communication,...
4999                0.56  Software Engineering, Project Management, Busi...

                   ai_skills salary_usd salary_change_vs_prev_year_percent  \
0     reinforcement learning      61586                              12.68
1                        NaN      62045                              -3.98
2                        NaN      27035                               3.55
3                        NaN      72894                              -2.80
4                        NaN      57215                               0.85
...                      ...        ...                                ...
4995                     NaN      41317                               4.62
4996                     NaN      37089                              -4.26
4997                     NaN      81651                              -4.95
4998  computer vision, MLOps     107897                              -0.23
4999                    LLMs      35755                              11.00

      automation_risk_score  reskilling_required  ai_job_displacement_risk  \
0                      0.11                 True                       Low
1                      0.71                False                      High
2                      0.86                False                      High
3                      0.70                False                       Low
4                      0.87                False                      High
...                     ...                  ...                       ...
4995                   0.88                False                       Low
4996                   0.79                False                       Low
4997                   0.64                False                       Low
4998                   0.33                 True                       Low
4999                   0.10                 True                       Low

      job_description_embedding_cluster industry_ai_adoption_stage
0                                    14                    Growing
1                                    19                   Emerging
2                                     2                   Emerging
3                                    15                   Emerging
4                                    13                   Emerging
...                                 ...                        ...
4995                                 17                    Growing
4996                                 13                    Growing
4997                                 19                    Growing
4998                                 14                   Emerging
4999                                 11                     Mature

[5000 rows x 22 columns]

In [24]:
import pandas as pd
df=pd.read_csv("students_data.csv")
df

  Student Name     Age  Gender  Marks        City
0         Ravi      20    Male   85.0     Chennai
1          Anu      21  FEMALE   90.0   Bangalore
2        Kiran     NaN    male   78.0   Hyderabad
3         Ravi      20    Male   85.0     Chennai
4        Meena  twenty  Female    NaN  Coimbatore
5       Suresh      22    MALE   88.0         NaN
6        Divya       -  female   92.0     Chennai
7         Arun      21     NaN   75.0     Madurai
8        Priya      23  Female   90.0   Bangalore

In [25]:
df["Age"]=df["Age"].fillna(0)
df["Marks"]=df["Marks"].fillna(0)
df["Gender"]=df["Gender"].fillna("unknown")
df["City"]=df["City"].fillna("unknown")

In [26]:
df

  Student Name     Age   Gender  Marks        City
0         Ravi      20     Male   85.0     Chennai
1          Anu      21   FEMALE   90.0   Bangalore
2        Kiran       0     male   78.0   Hyderabad
3         Ravi      20     Male   85.0     Chennai
4        Meena  twenty   Female    0.0  Coimbatore
5       Suresh      22     MALE   88.0     unknown
6        Divya       -   female   92.0     Chennai
7         Arun      21  unknown   75.0     Madurai
8        Priya      23   Female   90.0   Bangalore

In [27]:
df=df.drop_duplicates()
df

  Student Name     Age   Gender  Marks        City
0         Ravi      20     Male   85.0     Chennai
1          Anu      21   FEMALE   90.0   Bangalore
2        Kiran       0     male   78.0   Hyderabad
4        Meena  twenty   Female    0.0  Coimbatore
5       Suresh      22     MALE   88.0     unknown
6        Divya       -   female   92.0     Chennai
7         Arun      21  unknown   75.0     Madurai
8        Priya      23   Female   90.0   Bangalore

In [28]:
df["Age"]=df["Age"].replace(["twenty","-"],0)
df

  Student Name Age   Gender  Marks        City
0         Ravi  20     Male   85.0     Chennai
1          Anu  21   FEMALE   90.0   Bangalore
2        Kiran   0     male   78.0   Hyderabad
4        Meena   0   Female    0.0  Coimbatore
5       Suresh  22     MALE   88.0     unknown
6        Divya   0   female   92.0     Chennai
7         Arun  21  unknown   75.0     Madurai
8        Priya  23   Female   90.0   Bangalore

In [29]:
df.dtypes

Student Name        str
Age              object
Gender              str
Marks           float64
City                str
dtype: object

In [30]:
df["Age"]=df["Age"].astype(int)
df.dtypes

Student Name        str
Age               int64
Gender              str
Marks           float64
City                str
dtype: object

In [31]:
df.rename(columns={"Student Name":"SName"},inplace=True)

In [32]:
df

    SName  Age   Gender  Marks        City
0    Ravi   20     Male   85.0     Chennai
1     Anu   21   FEMALE   90.0   Bangalore
2   Kiran    0     male   78.0   Hyderabad
4   Meena    0   Female    0.0  Coimbatore
5  Suresh   22     MALE   88.0     unknown
6   Divya    0   female   92.0     Chennai
7    Arun   21  unknown   75.0     Madurai
8   Priya   23   Female   90.0   Bangalore

In [33]:
df["SName"]=df["SName"].str.upper()
df["Gender"]=df["Gender"].str.upper()
df["City"]=df["City"].str.upper()

In [34]:
df

    SName  Age   Gender  Marks        City
0    RAVI   20     MALE   85.0     CHENNAI
1     ANU   21   FEMALE   90.0   BANGALORE
2   KIRAN    0     MALE   78.0   HYDERABAD
4   MEENA    0   FEMALE    0.0  COIMBATORE
5  SURESH   22     MALE   88.0     UNKNOWN
6   DIVYA    0   FEMALE   92.0     CHENNAI
7    ARUN   21  UNKNOWN   75.0     MADURAI
8   PRIYA   23   FEMALE   90.0   BANGALORE

In [37]:
df.head(2)

  SName  Age  Gender  Marks       City
0  RAVI   20    MALE   85.0    CHENNAI
1   ANU   21  FEMALE   90.0  BANGALORE

In [38]:
df.tail(4)

    SName  Age   Gender  Marks       City
5  SURESH   22     MALE   88.0    UNKNOWN
6   DIVYA    0   FEMALE   92.0    CHENNAI
7    ARUN   21  UNKNOWN   75.0    MADURAI
8   PRIYA   23   FEMALE   90.0  BANGALORE

In [2]:
import pandas as pd
s=pd.Series([80,90,88],index=["Math","Science","English"])
print(s)

Math       80
Science    90
English    88
dtype: int64

In [35]:
d={
    "Name":['Riya','Selvi','Sivan'],
    "Marks":[85,78,90]
}
df=pd.DataFrame(d)
print(df)

    Name  Marks
0   Riya     85
1  Selvi     78
2  Sivan     90

In [36]:
print(df["Marks"])

0    85
1    78
2    90
Name: Marks, dtype: int64

In [37]:
print(df.loc[0])

Name     Riya
Marks      85
Name: 0, dtype: object

In [38]:
print(df[df["Marks"]>80])

    Name  Marks
0   Riya     85
2  Sivan     90

In [39]:
print(df.sort_values("Marks"))

    Name  Marks
1  Selvi     78
0   Riya     85
2  Sivan     90

In [40]:
print(df.sort_values("Name"))

    Name  Marks
0   Riya     85
1  Selvi     78
2  Sivan     90

In [41]:
df["Result"]=["Pass","Pass","Pass"]
print(df)

    Name  Marks Result
0   Riya     85   Pass
1  Selvi     78   Pass
2  Sivan     90   Pass

In [42]:
df.drop("Result",axis=1,inplace=True)
print(df)

    Name  Marks
0   Riya     85
1  Selvi     78
2  Sivan     90

In [45]:
print(df["Marks"].mean())
print(df["Marks"].sum())
print(df["Marks"].max())
print(df["Marks"].min())

84.33333333333333
253
90
78